// Copyright 2011 Google Inc. All Rights Reserved.
(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var m,aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ca=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},p=ca(this),da=function(){da=function(){};p.Symbol||(p.Symbol=ea)},fa=function(a,b){this.a=a;ba(this,"description",{configurable:!0,writable:!0,value:b})};fa.prototype.toString=function(){return this.a};
var ea=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new fa("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}(),ia=function(){da();var a=p.Symbol.iterator;a||(a=p.Symbol.iterator=p.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&ba(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ha(aa(this))}});ia=function(){}},ha=function(a){ia();a={next:a};a[p.Symbol.iterator]=function(){return this};return a},
q=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}},ja=function(a){if(!(a instanceof Array)){a=q(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a},ka="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},la;
if("function"==typeof Object.setPrototypeOf)la=Object.setPrototypeOf;else{var ma;a:{var na={qa:!0},oa={};try{oa.__proto__=na;ma=oa.qa;break a}catch(a){}ma=!1}la=ma?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var pa=la,t=function(a,b){a.prototype=ka(b.prototype);a.prototype.constructor=a;if(pa)pa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.V=b.prototype},qa=function(a,b){if(b){var c=p;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}},v=function(a,b){return Object.prototype.hasOwnProperty.call(a,
b)};qa("Object.setPrototypeOf",function(a){return a||pa});qa("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});qa("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
qa("WeakMap",function(a){function b(){}function c(k){var l=typeof k;return"object"===l&&null!==k||"function"===l}function d(k){if(!v(k,f)){var l=new b;ba(k,f,{value:l})}}function e(k){var l=Object[k];l&&(Object[k]=function(n){if(n instanceof b)return n;d(n);return l(n)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),n=new a([[k,2],[l,3]]);if(2!=n.get(k)||3!=n.get(l))return!1;n.delete(k);n.set(l,4);return!n.has(k)&&4==n.get(l)}catch(r){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var g=0,h=function(k){this.a=(g+=Math.random()+1).toString();if(k){k=q(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}};h.prototype.set=function(k,l){if(!c(k))throw Error("Invalid WeakMap key");d(k);if(!v(k,f))throw Error("WeakMap key fail: "+k);k[f][this.a]=l;return this};h.prototype.get=function(k){return c(k)&&v(k,f)?k[f][this.a]:void 0};h.prototype.has=function(k){return c(k)&&v(k,f)&&v(k[f],this.a)};
h.prototype.delete=function(k){return c(k)&&v(k,f)&&v(k[f],this.a)?delete k[f][this.a]:!1};return h});
qa("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var h=Object.seal({x:4}),k=new a(q([[h,"s"]]));if("s"!=k.get(h)||1!=k.size||k.get({x:4})||k.set({x:4},"t")!=k||2!=k.size)return!1;var l=k.entries(),n=l.next();if(n.done||n.value[0]!=h||"s"!=n.value[1])return!1;n=l.next();return n.done||4!=n.value[0].x||"t"!=n.value[1]||!l.next().done?!1:!0}catch(r){return!1}}())return a;ia();var b=new WeakMap,c=function(h){this.b={};this.a=
f();this.size=0;if(h){h=q(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}};c.prototype.set=function(h,k){h=0===h?0:h;var l=d(this,h);l.list||(l.list=this.b[l.id]=[]);l.o?l.o.value=k:(l.o={next:this.a,A:this.a.A,head:this.a,key:h,value:k},l.list.push(l.o),this.a.A.next=l.o,this.a.A=l.o,this.size++);return this};c.prototype.delete=function(h){h=d(this,h);return h.o&&h.list?(h.list.splice(h.index,1),h.list.length||delete this.b[h.id],h.o.A.next=h.o.next,h.o.next.A=h.o.A,h.o.head=null,
this.size--,!0):!1};c.prototype.clear=function(){this.b={};this.a=this.a.A=f();this.size=0};c.prototype.has=function(h){return!!d(this,h).o};c.prototype.get=function(h){return(h=d(this,h).o)&&h.value};c.prototype.entries=function(){return e(this,function(h){return[h.key,h.value]})};c.prototype.keys=function(){return e(this,function(h){return h.key})};c.prototype.values=function(){return e(this,function(h){return h.value})};c.prototype.forEach=function(h,k){for(var l=this.entries(),n;!(n=l.next()).done;)n=
n.value,h.call(k,n[1],n[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(h,k){var l=k&&typeof k;"object"==l||"function"==l?b.has(k)?l=b.get(k):(l=""+ ++g,b.set(k,l)):l="p_"+k;var n=h.b[l];if(n&&v(h.b,l))for(h=0;h<n.length;h++){var r=n[h];if(k!==k&&r.key!==r.key||k===r.key)return{id:l,list:n,index:h,o:r}}return{id:l,list:n,index:-1,o:void 0}},e=function(h,k){var l=h.a;return ha(function(){if(l){for(;l.head!=h.a;)l=l.A;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};
l=null}return{done:!0,value:void 0}})},f=function(){var h={};return h.A=h.next=h.head=h},g=0;return c});
qa("Promise",function(a){function b(){this.a=null}function c(g){return g instanceof e?g:new e(function(h){h(g)})}if(a)return a;b.prototype.b=function(g){if(null==this.a){this.a=[];var h=this;this.f(function(){h.i()})}this.a.push(g)};var d=p.setTimeout;b.prototype.f=function(g){d(g,0)};b.prototype.i=function(){for(;this.a&&this.a.length;){var g=this.a;this.a=[];for(var h=0;h<g.length;++h){var k=g[h];g[h]=null;try{k()}catch(l){this.h(l)}}}this.a=null};b.prototype.h=function(g){this.f(function(){throw g;
})};var e=function(g){this.b=0;this.f=void 0;this.a=[];var h=this.h();try{g(h.resolve,h.reject)}catch(k){h.reject(k)}};e.prototype.h=function(){function g(l){return function(n){k||(k=!0,l.call(h,n))}}var h=this,k=!1;return{resolve:g(this.u),reject:g(this.i)}};e.prototype.u=function(g){if(g===this)this.i(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof e)this.w(g);else{a:switch(typeof g){case "object":var h=null!=g;break a;case "function":h=!0;break a;default:h=!1}h?this.s(g):
this.l(g)}};e.prototype.s=function(g){var h=void 0;try{h=g.then}catch(k){this.i(k);return}"function"==typeof h?this.B(h,g):this.l(g)};e.prototype.i=function(g){this.j(2,g)};e.prototype.l=function(g){this.j(1,g)};e.prototype.j=function(g,h){if(0!=this.b)throw Error("Cannot settle("+g+", "+h+"): Promise already settled in state"+this.b);this.b=g;this.f=h;this.m()};e.prototype.m=function(){if(null!=this.a){for(var g=0;g<this.a.length;++g)f.b(this.a[g]);this.a=null}};var f=new b;e.prototype.w=function(g){var h=
this.h();g.$(h.resolve,h.reject)};e.prototype.B=function(g,h){var k=this.h();try{g.call(h,k.resolve,k.reject)}catch(l){k.reject(l)}};e.prototype.then=function(g,h){function k(u,z){return"function"==typeof u?function(lb){try{l(u(lb))}catch(mb){n(mb)}}:z}var l,n,r=new e(function(u,z){l=u;n=z});this.$(k(g,l),k(h,n));return r};e.prototype.catch=function(g){return this.then(void 0,g)};e.prototype.$=function(g,h){function k(){switch(l.b){case 1:g(l.f);break;case 2:h(l.f);break;default:throw Error("Unexpected state: "+
l.b);}}var l=this;null==this.a?f.b(k):this.a.push(k)};e.resolve=c;e.reject=function(g){return new e(function(h,k){k(g)})};e.race=function(g){return new e(function(h,k){for(var l=q(g),n=l.next();!n.done;n=l.next())c(n.value).$(h,k)})};e.all=function(g){var h=q(g),k=h.next();return k.done?c([]):new e(function(l,n){function r(lb){return function(mb){u[lb]=mb;z--;0==z&&l(u)}}var u=[],z=0;do u.push(void 0),z++,c(k.value).$(r(u.length-1),n),k=h.next();while(!k.done)})};return e});
var ra=ra||{},w=this||self,sa=/^[\w+/_-]+[=]{0,2}$/,ta=null,ua=function(a,b){a=a.split(".");b=b||w;for(var c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b},va=function(){},wa=function(a){a.ha=void 0;a.C=function(){return a.ha?a.ha:a.ha=new a}},x=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&
"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},xa=function(a){var b=x(a);return"array"==b||"object"==b&&"number"==typeof a.length},ya=function(a){return"function"==x(a)},y=function(a){var b=
typeof a;return"object"==b&&null!=a||"function"==b},za="closure_uid_"+(1E9*Math.random()>>>0),Aa=0,Ba=function(a,b,c){return a.call.apply(a.bind,arguments)},Ca=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}},A=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?
A=Ba:A=Ca;return A.apply(null,arguments)},Da=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}},Ea=Date.now||function(){return+new Date},Fa=function(a,b){function c(){}c.prototype=b.prototype;a.V=b.prototype;a.prototype=new c;a.prototype.constructor=a};var Ga=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},B=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Ha=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e="string"===typeof a?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d},Ia=Array.prototype.reduce?function(a,b,c){return Array.prototype.reduce.call(a,b,c)}:function(a,b,c){var d=c;B(a,function(e,f){d=b.call(void 0,d,e,f,a)});return d},Ja=function(a,b){a:{for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?null:"string"===typeof a?a.charAt(b):
a[b]},Ka=function(a){return Array.prototype.concat.apply([],arguments)},La=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Ma=function(a){for(var b=[],c=0;c<a;c++)b[c]="";return b};var Na=function(a){var b=0,c=!1,d=[],e=function(){b=0;c&&(c=!1,f())},f=function(){b=w.setTimeout(e,1E3);a.apply(void 0,d)};return function(g){d=arguments;b?c=!0:f()}};var Oa=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},Pa=function(a,b){return null!==a&&b in a},Qa=function(a){for(var b in a)delete a[b]},Ra="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),Sa=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ra.length;f++)c=Ra[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var C=function(a,b){this.a=a===Ta&&b||"";this.b=Ua};C.prototype.U=!0;C.prototype.T=function(){return this.a.toString()};C.prototype.ga=!0;C.prototype.fa=function(){return 1};var Ua={},Ta={};var Va=function(a){return/^[\s\xa0]*$/.test(a)},Wa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},db=function(a,b){if(b)a=a.replace(Xa,"&amp;").replace(Ya,"&lt;").replace(Za,"&gt;").replace($a,"&quot;").replace(ab,"&#39;").replace(bb,"&#0;");else{if(!cb.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Xa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ya,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Za,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace($a,
"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(ab,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(bb,"&#0;"))}return a},Xa=/&/g,Ya=/</g,Za=/>/g,$a=/"/g,ab=/'/g,bb=/\x00/g,cb=/[\x00&<>"']/,eb=function(a,b){return-1!=a.toLowerCase().indexOf(b.toLowerCase())},fb=function(a,b){return a<b?-1:a>b?1:0};var D=function(a,b){this.a=a===gb&&b||"";this.b=hb};D.prototype.U=!0;D.prototype.T=function(){return this.a.toString()};D.prototype.ga=!0;D.prototype.fa=function(){return 1};var ib=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,hb={},gb={};var E;a:{var jb=w.navigator;if(jb){var kb=jb.userAgent;if(kb){E=kb;break a}}E=""}var F=function(a){return-1!=E.indexOf(a)};var nb=function(){return F("Firefox")||F("FxiOS")},ob=function(){return(F("Chrome")||F("CriOS"))&&!F("Edge")};var G=function(){this.a="";this.f=pb;this.b=null};G.prototype.ga=!0;G.prototype.fa=function(){return this.b};G.prototype.U=!0;G.prototype.T=function(){return this.a.toString()};var qb=function(a){if(a instanceof G&&a.constructor===G&&a.f===pb)return a.a;x(a);return"type_error:SafeHtml"},pb={},rb=function(a,b){var c=new G;c.a=a;c.b=b;return c};rb("<!DOCTYPE html>",0);rb("",0);rb("<br>",0);var sb=function(a){return a=db(a,void 0)},tb=2147483648*Math.random()|0;var ub=function(){return F("iPhone")&&!F("iPod")&&!F("iPad")};var vb=function(a){vb[" "](a);return a};vb[" "]=va;var wb=function(a,b){try{return vb(a[b]),!0}catch(c){}return!1},yb=function(a,b){var c=xb;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var zb=F("Opera"),H=F("Trident")||F("MSIE"),Ab=F("Edge"),Bb=F("Gecko")&&!(eb(E,"WebKit")&&!F("Edge"))&&!(F("Trident")||F("MSIE"))&&!F("Edge"),Cb=eb(E,"WebKit")&&!F("Edge"),Db=function(){var a=w.document;return a?a.documentMode:void 0},Eb;
a:{var Fb="",Gb=function(){var a=E;if(Bb)return/rv:([^\);]+)(\)|;)/.exec(a);if(Ab)return/Edge\/([\d\.]+)/.exec(a);if(H)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Cb)return/WebKit\/(\S+)/.exec(a);if(zb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Gb&&(Fb=Gb?Gb[1]:"");if(H){var Hb=Db();if(null!=Hb&&Hb>parseFloat(Fb)){Eb=String(Hb);break a}}Eb=Fb}
var Ib=Eb,xb={},Jb=function(a){return yb(a,function(){for(var b=0,c=Wa(String(Ib)).split("."),d=Wa(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"";do{g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==g[0].length&&0==h[0].length)break;b=fb(0==g[1].length?0:parseInt(g[1],10),0==h[1].length?0:parseInt(h[1],10))||fb(0==g[2].length,0==h[2].length)||fb(g[2],h[2]);g=g[3];h=h[3]}while(0==b)}return 0<=b})},Kb;
if(w.document&&H){var Lb=Db();Kb=Lb?Lb:parseInt(Ib,10)||void 0}else Kb=void 0;var Mb=Kb;var Nb=nb(),Ob=ub()||F("iPod"),Pb=F("iPad"),Qb=F("Android")&&!(ob()||nb()||F("Opera")||F("Silk")),Rb=ob(),Sb=F("Safari")&&!(ob()||F("Coast")||F("Opera")||F("Edge")||F("Edg/")||F("OPR")||nb()||F("Silk")||F("Android"))&&!(ub()||F("iPad")||F("iPod"));var Tb=function(a,b,c){a.addEventListener&&a.addEventListener(b,c,!1)},Ub=function(a,b,c){a.removeEventListener&&a.removeEventListener(b,c,!1)},Vb=function(a){var b=void 0===b?{}:b;if(ya(window.CustomEvent))var c=new CustomEvent("rum_blp",b);else c=document.createEvent("CustomEvent"),c.initCustomEvent("rum_blp",!!b.bubbles,!!b.cancelable,b.detail);a.dispatchEvent(c)};var Wb=!H||9<=Number(Mb);var Yb=function(a,b){Oa(b,function(c,d){c&&"object"==typeof c&&c.U&&(c=c.T());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:Xb.hasOwnProperty(d)?a.setAttribute(Xb[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})},Xb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",
width:"width"},ac=function(a,b,c){var d=arguments,e=document,f=String(d[0]),g=d[1];if(!Wb&&g&&(g.name||g.type)){f=["<",f];g.name&&f.push(' name="',sb(g.name),'"');if(g.type){f.push(' type="',sb(g.type),'"');var h={};Sa(h,g);delete h.type;g=h}f.push(">");f=f.join("")}f=Zb(e,f);g&&("string"===typeof g?f.className=g:Array.isArray(g)?f.className=g.join(" "):Yb(f,g));2<d.length&&$b(e,f,d);return f},$b=function(a,b,c){function d(g){g&&b.appendChild("string"===typeof g?a.createTextNode(g):g)}for(var e=2;e<
c.length;e++){var f=c[e];!xa(f)||y(f)&&0<f.nodeType?d(f):B(bc(f)?La(f):f,d)}},Zb=function(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)},bc=function(a){if(a&&"number"==typeof a.length){if(y(a))return"function"==typeof a.item||"string"==typeof a.item;if(ya(a))return"function"==typeof a.item}return!1};var cc=function(a,b){a.google_image_requests||(a.google_image_requests=[]);var c=a.document.createElement("img");c.src=b;a.google_image_requests.push(c)};var dc=document,ec=window;var fc=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^\\/?#]*)@)?([^\\/?#]*?)(?::([0-9]+))?(?=[\\/?#]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,gc=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};var hc=function(a){try{return!!a&&null!=a.location.href&&wb(a,"foo")}catch(b){return!1}},ic=function(a,b){if(a)for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.call(void 0,a[c],c,a)},jc=/https?:\/\/[^\/]+/,kc=function(a){return(a=jc.exec(a))&&a[0]||""};var I=function(){this.l=this.l;this.i=this.i};I.prototype.l=!1;I.prototype.F=function(){this.l||(this.l=!0,this.v())};var lc=function(a,b){a.l?b():(a.i||(a.i=[]),a.i.push(b))};I.prototype.v=function(){if(this.i)for(;this.i.length;)this.i.shift()()};var mc=function(a){a&&"function"==typeof a.F&&a.F()};/*
 Copyright (c) Microsoft Corporation. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 this file except in compliance with the License. You may obtain a copy of the
 License at http://www.apache.org/licenses/LICENSE-2.0

 THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
 WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
 MERCHANTABLITY OR NON-INFRINGEMENT.

 See the Apache Version 2.0 License for specific language governing permissions
 and limitations under the License.
*/
var nc=function(a){a=void 0===a?w:a;var b=a.context||a.AMP_CONTEXT_DATA;if(!b)try{b=a.parent.context||a.parent.AMP_CONTEXT_DATA}catch(c){}try{if(b&&b.pageViewId&&b.canonicalUrl)return b}catch(c){}return null};var oc=!!window.google_async_iframe_id,pc=oc&&window.parent||window,qc=function(){if(oc&&!hc(pc)){var a="."+dc.domain;try{for(;2<a.split(".").length&&!hc(pc);)dc.domain=a=a.substr(a.indexOf(".")+1),pc=window.parent}catch(b){}hc(pc)||(pc=window)}return pc};var rc=function(a,b){var c=void 0===c?{}:c;this.error=a;this.context=b.context;this.msg=b.message||"";this.id=b.id||"jserror";this.meta=c};var sc=/^https?:\/\/(\w|-)+\.cdn\.ampproject\.(net|org)(\?|\/|$)/,wc=function(a){a=a||tc();for(var b=new uc(w.location.href,w,!1),c=null,d=a.length-1,e=d;0<=e;--e){var f=a[e];!c&&sc.test(f.url)&&(c=f);if(f.url&&!f.ia){b=f;break}}e=null;f=a.length&&a[d].url;0!=b.depth&&f&&(e=a[d]);return new vc(b,e,c)},tc=function(){var a=w,b=[],c=null;do{var d=a;if(hc(d)){var e=d.location.href;c=d.document&&d.document.referrer||null}else e=c,c=null;b.push(new uc(e||"",d));try{a=d.parent}catch(f){a=null}}while(a&&
d!=a);d=0;for(a=b.length-1;d<=a;++d)b[d].depth=a-d;d=w;if(d.location&&d.location.ancestorOrigins&&d.location.ancestorOrigins.length==b.length-1)for(a=1;a<b.length;++a)e=b[a],e.url||(e.url=d.location.ancestorOrigins[a-1]||"",e.ia=!0);return b},vc=function(a,b,c){this.a=a;this.b=b;this.f=c},uc=function(a,b,c){this.url=a;this.na=b;this.ia=!!c;this.depth=null};var xc=function(){this.f="&";this.h=!1;this.b={};this.i=0;this.a=[]},yc=function(a,b){var c={};c[a]=b;return[c]},Ac=function(a,b,c,d,e){var f=[];ic(a,function(g,h){(g=zc(g,b,c,d,e))&&f.push(h+"="+g)});return f.join(b)},zc=function(a,b,c,d,e){if(null==a)return"";b=b||"&";c=c||",$";"string"==typeof c&&(c=c.split(""));if(a instanceof Array){if(d=d||0,d<c.length){for(var f=[],g=0;g<a.length;g++)f.push(zc(a[g],b,c,d+1,e));return f.join(c[d])}}else if("object"==typeof a)return e=e||0,2>e?encodeURIComponent(Ac(a,
b,c,d,e+1)):"...";return encodeURIComponent(String(a))},Bc=function(a,b,c,d){a.a.push(b);a.b[b]=yc(c,d)},Dc=function(a,b){b+="//pagead2.googlesyndication.com/pagead/gen_204?id=jserror&";var c=Cc(a)-27;if(0>c)return"";a.a.sort(function(n,r){return n-r});for(var d=null,e="",f=0;f<a.a.length;f++)for(var g=a.a[f],h=a.b[g],k=0;k<h.length;k++){if(!c){d=null==d?g:d;break}var l=Ac(h[k],a.f,",$");if(l){l=e+l;if(c>=l.length){c-=l.length;b+=l;e=a.f;break}a.h&&(e=c,l[e-1]==a.f&&--e,b+=l.substr(0,e),e=a.f,c=0);
d=null==d?g:d}}a="";null!=d&&(a=e+"trn="+d);return b+a+""},Cc=function(a){var b=1,c;for(c in a.b)b=c.length>b?c.length:b;return 3997-b-a.f.length-1};var Ec=function(a,b,c){if(.01>(c?a.a:Math.random()))try{if(b instanceof xc)var d=b;else d=new xc,ic(b,function(f,g){var h=d,k=h.i++;f=yc(g,f);h.a.push(k);h.b[k]=f});var e=Dc(d,a.b);e&&cc(w,e)}catch(f){}};var Fc=null;var Gc=function(a,b,c){this.label=a;this.type=b;this.value=c;this.duration=0;this.uniqueId=Math.random();this.slotId=void 0};var J=w.performance,Hc=!!(J&&J.mark&&J.measure&&J.clearMarks),Ic=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a;if(a=Hc){var b;if(null===Fc){Fc="";try{a="";try{a=w.top.location.hash}catch(c){a=w.location.hash}a&&(Fc=(b=a.match(/\bdeid=([\d,]+)/))?b[1]:"")}catch(c){}}b=Fc;a=!!b.indexOf&&0<=b.indexOf("1337")}return a}),Jc=function(a,b){this.events=[];this.a=b||w;var c=null;b&&(b.google_js_reporting_queue=b.google_js_reporting_queue||[],this.events=b.google_js_reporting_queue,
c=b.google_measure_js_timing);this.j=Ic()||(null!=c?c:Math.random()<a)};Jc.prototype.l=function(){this.j=!1;this.events!=this.a.google_js_reporting_queue&&(Ic()&&B(this.events,Kc),this.events.length=0)};var Kc=function(a){a&&J&&Ic()&&(J.clearMarks("goog_"+a.label+"_"+a.uniqueId+"_start"),J.clearMarks("goog_"+a.label+"_"+a.uniqueId+"_end"))};
Jc.prototype.start=function(a,b){if(!this.j)return null;var c=void 0===c?w:c;c=c.performance;(c=c&&c.now?c.now():null)||(c=(c=w.performance)&&c.now&&c.timing?Math.floor(c.now()+c.timing.navigationStart):Ea());a=new Gc(a,b,c);b="goog_"+a.label+"_"+a.uniqueId+"_start";J&&Ic()&&J.mark(b);return a};var Mc=function(){this.h=Lc;this.a=null;this.b=!1};Mc.prototype.i=function(a){this.a=a};Mc.prototype.l=function(a){this.b=a};
Mc.prototype.f=function(a,b){try{var c=new xc;c.h=!0;Bc(c,1,"context",a);b.error&&b.meta&&b.id||(b=new rc(b,{message:Nc(b)}));b.msg&&Bc(c,2,"msg",b.msg.substring(0,512));var d=b.meta||{};if(this.a)try{this.a(d)}catch(f){}b=[d];c.a.push(3);c.b[3]=b;var e=wc();e.b&&Bc(c,4,"top",e.b.url||"");Bc(c,5,"url",e.a.url||"");Ec(this.h,c,this.b)}catch(f){try{Ec(this.h,{context:"ecmserr",rctx:a,msg:Nc(f),url:e&&e.a.url},this.b)}catch(g){}}};
var Nc=function(a){var b=a.toString();a.name&&-1==b.indexOf(a.name)&&(b+=": "+a.name);a.message&&-1==b.indexOf(a.message)&&(b+=": "+a.message);if(a.stack){a=a.stack;var c=b;try{-1==a.indexOf(c)&&(a=c+"\n"+a);for(var d;a!=d;)d=a,a=a.replace(/((https?:\/..*\/)[^\/:]*:\d+(?:.|\n)*)\2/,"$1");b=a.replace(/\n */g,"\n")}catch(e){b=c}}return b};var Oc=function(){this.a=null;this.b=!1;this.h=Math.random()};Oc.prototype.i=function(a){this.a=a};Oc.prototype.l=function(a){this.b=a};
Oc.prototype.f=function(a,b){var c;if(!((this.b?this.h:Math.random())>(void 0===d?.01:d)||(b.error&&b.meta&&b.id||(b=new rc(b,{context:a,id:void 0===c?"jserror":c})),this.a&&(b.meta={},this.a&&this.a(b.meta)),w.google_js_errors=w.google_js_errors||[],w.google_js_errors.push(b),w.error_rep_loaded))){b=w.document;a=b.createElement("script");var d=new C(Ta,w.location.protocol+"//pagead2.googlesyndication.com/pagead/js/err_rep.js");d instanceof C&&d.constructor===C&&d.b===Ua?d=d.a:(x(d),d="type_error:TrustedResourceUrl");
a.src=d;if(null===ta)b:{d=w.document;if((d=d.querySelector&&d.querySelector("script[nonce]"))&&(d=d.nonce||d.getAttribute("nonce"))&&sa.test(d)){ta=d;break b}ta=""}(d=ta)&&a.setAttribute("nonce",d);(b=b.getElementsByTagName("script")[0])&&b.parentNode&&b.parentNode.insertBefore(a,b);w.error_rep_loaded=!0}};var Lc,Pc,K=qc(),Qc=new Jc(1,K);Lc=new function(){var a=void 0===a?ec:a;this.b="http:"===a.location.protocol?"http:":"https:";this.a=Math.random()};"number"!==typeof K.google_srt&&(K.google_srt=Math.random());var Rc=Lc,Sc=K.google_srt;0<=Sc&&1>=Sc&&(Rc.a=Sc);Pc=new Mc;
Pc.i(function(a){var b=ec.jerExpIds;if("array"==x(b)&&0!==b.length){var c=a.eid;if(c){b=[].concat(ja(c.split(",")),ja(b));c={};for(var d=0,e=0;e<b.length;){var f=b[e++];var g=f;g=y(g)?"o"+(Object.prototype.hasOwnProperty.call(g,za)&&g[za]||(g[za]=++Aa)):(typeof g).charAt(0)+g;Object.prototype.hasOwnProperty.call(c,g)||(c[g]=!0,b[d++]=f)}b.length=d;a.eid=b.join(",")}else a.eid=b.join(",")}(b=ec.jerUserAgent)&&(a.useragent=b)});Pc.l(!0);
"complete"==K.document.readyState?K.google_measure_js_timing||Qc.l():Qc.j&&Tb(K,"load",function(){K.google_measure_js_timing||Qc.l()});var Tc=function(){this.S={}},Uc=null,Vc={},Wc=(Vc[8]="google_prev_ad_formats_by_region",Vc[9]="google_prev_ad_slotnames_by_region",Vc);var Xc=!H||9<=Number(Mb),Yc=H&&!Jb("9"),Zc=function(){if(!w.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{w.addEventListener("test",va,b),w.removeEventListener("test",va,b)}catch(c){}return a}();var L=function(a,b){this.type=a;this.a=this.target=b;this.defaultPrevented=!1};L.prototype.f=function(){this.defaultPrevented=!0};var ad=function(a,b){L.call(this,a?a.type:"");this.relatedTarget=this.a=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.pointerId=0;this.pointerType="";this.b=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.a=b;(b=a.relatedTarget)?Bb&&(wb(b,"nodeName")||(b=null)):"mouseover"==c?b=a.fromElement:"mouseout"==
c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||
0;this.pointerType="string"===typeof a.pointerType?a.pointerType:$c[a.pointerType]||"";this.b=a;a.defaultPrevented&&this.f()}};Fa(ad,L);var $c={2:"touch",3:"pen",4:"mouse"};ad.prototype.f=function(){ad.V.f.call(this);var a=this.b;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Yc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var bd="closure_listenable_"+(1E6*Math.random()|0),cd=function(a){return!(!a||!a[bd])},dd=0;var ed=function(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.aa=e;this.key=++dd;this.N=this.Z=!1},fd=function(a){a.N=!0;a.listener=null;a.a=null;a.src=null;a.aa=null};var gd=function(a){this.src=a;this.a={};this.b=0};gd.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var g=hd(a,b,d,e);-1<g?(b=a[g],c||(b.Z=!1)):(b=new ed(b,this.src,f,!!d,e),b.Z=c,a.push(b));return b};
var id=function(a,b){var c=b.type;if(c in a.a){var d=a.a[c],e=Ga(d,b),f;(f=0<=e)&&Array.prototype.splice.call(d,e,1);f&&(fd(b),0==a.a[c].length&&(delete a.a[c],a.b--))}},jd=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=hd(a,c,d,e));return-1<b?a[b]:null},hd=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.N&&f.listener==b&&f.capture==!!c&&f.aa==d)return e}return-1};var kd="closure_lm_"+(1E6*Math.random()|0),ld={},md=0,od=function(a,b,c,d,e){if(d&&d.once)return nd(a,b,c,d,e);if(Array.isArray(b)){for(var f=0;f<b.length;f++)od(a,b[f],c,d,e);return null}c=pd(c);return cd(a)?a.H(b,c,y(d)?!!d.capture:!!d,e):qd(a,b,c,!1,d,e)},qd=function(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var g=y(e)?!!e.capture:!!e,h=rd(a);h||(a[kd]=h=new gd(a));c=h.add(b,c,d,g,f);if(c.a)return c;d=sd();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)Zc||(e=g),void 0===e&&(e=!1),
a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(td(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");md++;return c},sd=function(){var a=ud,b=Xc?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b},nd=function(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)nd(a,b[f],c,d,e);return null}c=pd(c);return cd(a)?a.b.add(String(b),
c,!0,y(d)?!!d.capture:!!d,e):qd(a,b,c,!0,d,e)},vd=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)vd(a,b[f],c,d,e);else d=y(d)?!!d.capture:!!d,c=pd(c),cd(a)?a.ja(b,c,d,e):a&&(a=rd(a))&&(b=jd(a,b,c,d,e))&&wd(b)},wd=function(a){if("number"!==typeof a&&a&&!a.N){var b=a.src;if(cd(b))id(b.b,a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(td(c),d):b.addListener&&b.removeListener&&b.removeListener(d);md--;(c=rd(b))?(id(c,
a),0==c.b&&(c.src=null,b[kd]=null)):fd(a)}}},td=function(a){return a in ld?ld[a]:ld[a]="on"+a},yd=function(a,b,c,d){var e=!0;if(a=rd(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.N&&(f=xd(f,d),e=e&&!1!==f)}return e},xd=function(a,b){var c=a.listener,d=a.aa||a.src;a.Z&&wd(a);return c.call(d,b)},ud=function(a,b){if(a.N)return!0;if(!Xc){var c=b||ua("window.event");b=new ad(c,this);var d=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var e=!1;if(0==c.keyCode)try{c.keyCode=
-1;break a}catch(g){e=!0}if(e||void 0==c.returnValue)c.returnValue=!0}c=[];for(e=b.a;e;e=e.parentNode)c.push(e);a=a.type;for(e=c.length-1;0<=e;e--){b.a=c[e];var f=yd(c[e],a,!0,b);d=d&&f}for(e=0;e<c.length;e++)b.a=c[e],f=yd(c[e],a,!1,b),d=d&&f}return d}return xd(a,new ad(b,this))},rd=function(a){a=a[kd];return a instanceof gd?a:null},zd="__closure_events_fn_"+(1E9*Math.random()>>>0),pd=function(a){if(ya(a))return a;a[zd]||(a[zd]=function(b){return a.handleEvent(b)});return a[zd]};var Cd=function(a){var b=[];Ad(new Bd,a,b);return b.join("")},Bd=function(){},Ad=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(Array.isArray(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),Ad(a,d[f],c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");e="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(f=b[d],"function"!=typeof f&&(c.push(e),Dd(d,c),c.push(":"),Ad(a,f,c),
e=","));c.push("}");return}}switch(typeof b){case "string":Dd(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("Unknown type: "+typeof b);}}},Ed={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Fd=/\uffff/.test("\uffff")?/[\\"\x00-\x1f\x7f-\uffff]/g:/[\\"\x00-\x1f\x7f-\xff]/g,Dd=function(a,b){b.push('"',a.replace(Fd,
function(c){var d=Ed[c];d||(d="\\u"+(c.charCodeAt(0)|65536).toString(16).substr(1),Ed[c]=d);return d}),'"')};var M=function(){I.call(this);this.b=new gd(this);this.da=this;this.K=null};Fa(M,I);M.prototype[bd]=!0;m=M.prototype;m.addEventListener=function(a,b,c,d){od(this,a,b,c,d)};m.removeEventListener=function(a,b,c,d){vd(this,a,b,c,d)};
m.dispatchEvent=function(a){var b,c=this.K;if(c)for(b=[];c;c=c.K)b.push(c);c=this.da;var d=a.type||a;if("string"===typeof a)a=new L(a,c);else if(a instanceof L)a.target=a.target||c;else{var e=a;a=new L(d,c);Sa(a,e)}e=!0;if(b)for(var f=b.length-1;0<=f;f--){var g=a.a=b[f];e=Gd(g,d,!0,a)&&e}g=a.a=c;e=Gd(g,d,!0,a)&&e;e=Gd(g,d,!1,a)&&e;if(b)for(f=0;f<b.length;f++)g=a.a=b[f],e=Gd(g,d,!1,a)&&e;return e};
m.v=function(){M.V.v.call(this);if(this.b){var a=this.b,b=0,c;for(c in a.a){for(var d=a.a[c],e=0;e<d.length;e++)++b,fd(d[e]);delete a.a[c];a.b--}}this.K=null};m.H=function(a,b,c,d){return this.b.add(String(a),b,!1,c,d)};m.ja=function(a,b,c,d){var e=this.b;a=String(a).toString();if(a in e.a){var f=e.a[a];b=hd(f,b,c,d);-1<b&&(fd(f[b]),Array.prototype.splice.call(f,b,1),0==f.length&&(delete e.a[a],e.b--))}};
var Gd=function(a,b,c,d){b=a.b.a[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.N&&g.capture==c){var h=g.listener,k=g.aa||g.src;g.Z&&id(a.b,g);e=!1!==h.call(k,d)&&e}}return e&&!d.defaultPrevented};var Hd=function(a,b,c){if(ya(a))c&&(a=A(a,c));else if(a&&"function"==typeof a.handleEvent)a=A(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:w.setTimeout(a,b||0)};var Id="StopIteration"in w?w.StopIteration:{message:"StopIteration",stack:""},Jd=function(){};Jd.prototype.next=function(){throw Id;};Jd.prototype.pa=function(){return this};var N=function(a,b){this.b={};this.a=[];this.h=this.f=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof N)for(c=a.L(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])};N.prototype.D=function(){Kd(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};N.prototype.L=function(){Kd(this);return this.a.concat()};
N.prototype.isEmpty=function(){return 0==this.f};N.prototype.clear=function(){this.b={};this.h=this.f=this.a.length=0};var Kd=function(a){if(a.f!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];O(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.f!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],O(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};m=N.prototype;m.get=function(a,b){return O(this.b,a)?this.b[a]:b};m.set=function(a,b){O(this.b,a)||(this.f++,this.a.push(a),this.h++);this.b[a]=b};
m.forEach=function(a,b){for(var c=this.L(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};m.clone=function(){return new N(this)};m.pa=function(a){Kd(this);var b=0,c=this.h,d=this,e=new Jd;e.next=function(){if(c!=d.h)throw Error("The map has changed since the iterator was created");if(b>=d.a.length)throw Id;var f=d.a[b++];return a?f:d.b[f]};return e};var O=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var P=function(a){this.b=this.j=this.h="";this.m=null;this.i=this.f="";this.l=!1;var b;a instanceof P?(this.l=a.l,Ld(this,a.h),this.j=a.j,this.b=a.b,Md(this,a.m),this.f=a.f,Nd(this,a.a.clone()),this.i=a.i):a&&(b=String(a).match(fc))?(this.l=!1,Ld(this,b[1]||"",!0),this.j=Od(b[2]||""),this.b=Od(b[3]||"",!0),Md(this,b[4]),this.f=Od(b[5]||"",!0),Nd(this,b[6]||"",!0),this.i=Od(b[7]||"")):(this.l=!1,this.a=new Q(null,this.l))};
P.prototype.toString=function(){var a=[],b=this.h;b&&a.push(Pd(b,Qd,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.j)&&a.push(Pd(b,Qd,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.m,null!=c&&a.push(":",String(c));if(c=this.f)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(Pd(c,"/"==c.charAt(0)?Rd:Sd,!0));(c=this.a.toString())&&a.push("?",c);(c=this.i)&&a.push("#",Pd(c,Td));return a.join("")};
P.prototype.resolve=function(a){var b=this.clone(),c=!!a.h;c?Ld(b,a.h):c=!!a.j;c?b.j=a.j:c=!!a.b;c?b.b=a.b:c=null!=a.m;var d=a.f;if(c)Md(b,a.m);else if(c=!!a.f){if("/"!=d.charAt(0))if(this.b&&!this.f)d="/"+d;else{var e=b.f.lastIndexOf("/");-1!=e&&(d=b.f.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var f=[],g=0;g<e.length;){var h=e[g++];"."==h?d&&g==e.length&&f.push(""):".."==h?((1<f.length||1==f.length&&
""!=f[0])&&f.pop(),d&&g==e.length&&f.push("")):(f.push(h),d=!0)}d=f.join("/")}else d=e}c?b.f=d:c=""!==a.a.toString();c?Nd(b,a.a.clone()):c=!!a.i;c&&(b.i=a.i);return b};P.prototype.clone=function(){return new P(this)};
var Ld=function(a,b,c){a.h=c?Od(b,!0):b;a.h&&(a.h=a.h.replace(/:$/,""))},Md=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.m=b}else a.m=null},Nd=function(a,b,c){b instanceof Q?(a.a=b,Ud(a.a,a.l)):(c||(b=Pd(b,Vd)),a.a=new Q(b,a.l))},Od=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},Pd=function(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,Wd),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},Wd=function(a){a=
a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Qd=/[#\/\?@]/g,Sd=/[#\?:]/g,Rd=/[#\?]/g,Vd=/[#\?@]/g,Td=/#/g,Q=function(a,b){this.b=this.a=null;this.f=a||null;this.h=!!b},R=function(a){a.a||(a.a=new N,a.b=0,a.f&&gc(a.f,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};Q.prototype.add=function(a,b){R(this);this.f=null;a=Xd(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b+=1;return this};
var Yd=function(a,b){R(a);b=Xd(a,b);O(a.a.b,b)&&(a.f=null,a.b-=a.a.get(b).length,a=a.a,O(a.b,b)&&(delete a.b[b],a.f--,a.h++,a.a.length>2*a.f&&Kd(a)))};Q.prototype.clear=function(){this.a=this.f=null;this.b=0};Q.prototype.isEmpty=function(){R(this);return 0==this.b};var Zd=function(a,b){R(a);b=Xd(a,b);return O(a.a.b,b)};m=Q.prototype;m.forEach=function(a,b){R(this);this.a.forEach(function(c,d){B(c,function(e){a.call(b,e,d,this)},this)},this)};
m.L=function(){R(this);for(var a=this.a.D(),b=this.a.L(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};m.D=function(a){R(this);var b=[];if("string"===typeof a)Zd(this,a)&&(b=Ka(b,this.a.get(Xd(this,a))));else{a=this.a.D();for(var c=0;c<a.length;c++)b=Ka(b,a[c])}return b};m.set=function(a,b){R(this);this.f=null;a=Xd(this,a);Zd(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};
m.get=function(a,b){if(!a)return b;a=this.D(a);return 0<a.length?String(a[0]):b};m.toString=function(){if(this.f)return this.f;if(!this.a)return"";for(var a=[],b=this.a.L(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.D(d);for(var f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}}return this.f=a.join("&")};m.clone=function(){var a=new Q;a.f=this.f;this.a&&(a.a=this.a.clone(),a.b=this.b);return a};
var Xd=function(a,b){b=String(b);a.h&&(b=b.toLowerCase());return b},Ud=function(a,b){b&&!a.h&&(R(a),a.f=null,a.a.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(Yd(this,d),Yd(this,e),0<c.length&&(this.f=null,this.a.set(Xd(this,e),La(c)),this.b+=c.length))},a));a.h=b};var $d="://secure-...imrworldwide.com/ ://cdn.imrworldwide.com/ ://aksecure.imrworldwide.com/ ://[^.]*.moatads.com ://youtube[0-9]+.moatpixel.com ://pm.adsafeprotected.com/youtube ://pm.test-adsafeprotected.com/youtube ://e[0-9]+.yt.srs.doubleverify.com www.google.com/pagead/xsul www.youtube.com/pagead/slav".split(" "),ae=/\bocr\b/,be=0,S={},ce=function(a){if(Va(null==a?"":String(a)))return!1;if(0<=a.indexOf("://pagead2.googlesyndication.com/pagead/gen_204?id=yt3p&sr=1&"))return!0;try{var b=new P(a)}catch(c){return null!=
Ja($d,function(d){return 0<a.search(d)})}return b.i.match(ae)?!0:null!=Ja($d,function(c){return null!=a.match(c)})},ge=function(a){if(a&&(a=de(a),!Va(a))){var b='javascript:"<body><img src=\\""+'+a+'+"\\"></body>"';ee(function(c){fe(c?b:'javascript:"<body><object data=\\""+'+a+'+"\\" type=\\"text/html\\" width=1 height=1 style=\\"visibility:hidden;\\"></body>"')})}},fe=function(a){var b=ac("IFRAME",{src:a,style:"display:none"});a=(9==b.nodeType?b:b.ownerDocument||b.document).body;var c=Hd(function(){wd(d);
b&&b.parentNode&&b.parentNode.removeChild(b)},15E3);var d=nd(b,["load","error"],function(){Hd(function(){w.clearTimeout(c);b&&b.parentNode&&b.parentNode.removeChild(b)},5E3)});a.appendChild(b)},ee=function(a){var b=S.imageLoadingEnabled;if(null!=b)a(b);else{var c=!1;he(function(d,e){delete S[e];c||(c=!0,null==S.imageLoadingEnabled&&(S.imageLoadingEnabled=d),a(d))})}},he=function(a){var b=new Image,c=""+be++;S[c]=b;b.onload=function(){clearTimeout(d);a(!0,c)};var d=setTimeout(function(){a(!1,c)},300);
b.src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="},ie=function(a){if(a){var b=Zb(document,"OBJECT");b.data=a;b.width="1";b.height="1";b.style.visibility="hidden";var c=""+be++;S[c]=b;b.onload=b.onerror=function(){delete S[c]};document.body.appendChild(b)}},je=function(a){if(a){var b=new Image,c=""+be++;S[c]=b;b.onload=b.onerror=function(){delete S[c]};b.src=a}},ke=function(a){a&&ee(function(b){b?je(a):ie(a)})},de=function(a){a instanceof D||(a="object"==typeof a&&
a.U?a.T():String(a),ib.test(a)||(a="about:invalid#zClosurez"),a=new D(gb,a));if(a instanceof D&&a.constructor===D&&a.b===hb)var b=a.a;else x(a),b="type_error:SafeUrl";if("about:invalid#zClosurez"===b)return"";if(b instanceof G)a=b;else{var c="object"==typeof b;a=null;c&&b.ga&&(a=b.fa());b=db(c&&b.U?b.T():String(b));a=rb(b,a)}a=qb(a).toString();return encodeURIComponent(String(Cd(a)))};function le(){var a=E;return eb(a,"AppleTV")||eb(a,"Apple TV")||eb(a,"CFNetwork")||eb(a,"tvOS")};var me=function(a){var b;a.visibilityState?b="visibilitychange":a.mozVisibilityState?b="mozvisibilitychange":a.webkitVisibilityState&&(b="webkitvisibilitychange");return b};var ne=function(a){a=a._google_rum_ns_=a._google_rum_ns_||{};return a.pq=a.pq||[]};var oe=function(a,b,c){ic(b,function(d,e){var f=c&&c[e];!d&&0!==d||f||(a+="&"+encodeURIComponent(e)+"="+encodeURIComponent(String(d)),c&&(c[e]=!0))});return a},ue=function(a,b,c,d,e,f,g,h){f=void 0===f?Infinity:f;g=void 0===g?!1:g;Jc.call(this,a,h);var k=this;this.w=0;this.P=f;this.W=b;this.B=c;this.R=d;this.X=e;a=this.a.navigator;this.J=!("csi.gstatic.com"!==this.B||!a||!a.sendBeacon);this.h={};this.u={};this.a.performance&&this.a.performance.now||pe(this,"dat",1);a&&a.deviceMemory&&pe(this,"dmc",
a.deviceMemory);this.Y=!g;this.O=function(){k.a.setTimeout(function(){return T(k)},1100)};this.ea=[];this.K=function(){qe(k,1)};this.I=function(){qe(k,2)};this.da=Na(function(){T(k)});this.oa=function(){var n=k.a.document;(null!=n.hidden?n.hidden:null!=n.mozHidden?n.mozHidden:null!=n.webkitHidden&&n.webkitHidden)&&k.da()};this.m=this.a.setTimeout(function(){return T(k)},5E3);this.i={};this.f=b.length+c.length+d.length+e.length+3;this.b=0;B(this.events,function(n){var r="met."+n.type,u="number"===
typeof n.value?Math.round(n.value).toString(36):n.value,z=Math.round(n.duration);n=""+n.label+(null!=n.slotId?"_"+n.slotId:"")+("."+u)+(0<z?"_"+z.toString(36):"");re(k,r,n,!0,"~")});this.s=[];b=ne(this.a);var l=function(n){var r=n[0];n=n[1];var u=r.length+n.length+2;8E3<k.f+k.b+u&&T(k);k.s.push([r,n]);k.b+=u;6E3<=k.f+k.b&&T(k);return 0};B(b,function(n){return l(n)});b.length=0;b.push=l;se(this);te(this)};t(ue,Jc);
var te=function(a){"complete"===a.a.document.readyState?a.a.setTimeout(function(){return T(a)},0):Tb(a.a,"load",a.O);var b=me(a.a.document);"undefined"!==typeof b&&Tb(a.a,b,a.oa);Tb(a.a,"unload",a.K);Tb(a.a,"pagehide",a.I)},pe=function(a,b,c){c=String(c);a.f=null!=a.h[b]?a.f+(c.length-a.h[b].length):a.f+(b.length+c.length+2);a.h[b]=c},ve=function(a){null!=a.h.uet&&(a.f-=3+a.h.uet.length+2,delete a.h.uet)},re=function(a,b,c,d,e){e=void 0===e?"":e;var f=null==a.i[b]?b.length+c.length+2:d?c.length+(void 0===
e?"":e).length:c.length-a.i[b].length;8E3<a.f+a.b+f&&(T(a),f=b.length+c.length+2);a.i[b]=d&&null!=a.i[b]?a.i[b]+(""+(void 0===e?"":e)+c):c;a.b+=f;6E3<=a.f+a.b&&T(a)},T=function(a){if(a.j&&a.Y){try{if(a.b){var b=a.i;a.w++;var c=we(a,b);b=!1;try{b=!!(a.J&&a.a.navigator&&a.a.navigator.sendBeacon(c,null))}catch(d){a.J=!1}b||cc(a.a,c);se(a);a.w===a.P&&a.l()}}catch(d){(new Oc).f(358,d)}a.i={};a.b=0;a.events.length=0;a.a.clearTimeout(a.m);a.m=0}},we=function(a,b){var c=a.W+"//"+a.B+a.R+a.X,d={};c=oe(c,a.h,
d);c=oe(c,b,d);a.a.google_timing_params&&(c=oe(c,a.a.google_timing_params,d),a.a.google_timing_params=void 0);B(a.s,function(e){var f=q(e);e=f.next().value;f=f.next().value;var g={};c=oe(c,(g[e]=f,g))});a.s.length=0;return c},se=function(a){pe(a,"puid",(a.w+1).toString(36)+"~"+Ea().toString(36))};ue.prototype.l=function(){Jc.prototype.l.call(this);this.a.clearTimeout(this.m);this.b=this.m=0;this.i={};Qa(this.u);Qa(this.h);Ub(this.a,"load",this.O);Ub(this.a,"unload",this.K);Ub(this.a,"pagehide",this.I)};
var qe=function(a,b){pe(a,"uet",b);B(a.ea,function(c){try{c()}catch(d){}});Vb(a.a);T(a);ve(a)};var U=function(){this.a=new ue(1,"https:","csi.gstatic.com","/csi?v=2&s=","ima",void 0,!0);if(Uc)var a=Uc;else{a=((a=nc())?hc(a.master)?a.master:null:null)||qc();var b=a.google_persistent_state_async;a=null!=b&&"object"==typeof b&&null!=b.S&&"object"==typeof b.S?Uc=b:a.google_persistent_state_async=Uc=new Tc}b=qc();var c=nc(b);if(c)(c=c||nc())?(b=c.pageViewId,c=c.clientId,"string"===typeof c&&(b+=c.replace(/\D/g,"").substr(0,6))):b=null,b=+b;else{c=0;for(var d=b,e=0;b&&b!=b.parent;)b=b.parent,e++,
hc(b)&&(d=b,c=e);b=d;(c=b.google_global_correlator)||(b.google_global_correlator=c=1+Math.floor(Math.random()*Math.pow(2,43)));b=c}c=Wc[7]||"google_ps_7";a=a.S;d=a[c];a=void 0===d?a[c]=b:d;null!=a&&pe(this.a,"c",a);a=parseInt(this.a.h.c,10)/2;null!=a&&pe(this.a,"slotId",a)},V=function(a,b,c){if(null!=c){a=a.a;var d=b+"="+c;a.u[d]||(re(a,b,c,!1),1E3>d.length&&(a.u[d]=!0))}};wa(U);var xe="ad.doubleclick.net bid.g.doubleclick.net ggpht.com google.co.uk google.com googleads.g.doubleclick.net googleads4.g.doubleclick.net googleadservices.com googlesyndication.com googleusercontent.com gstatic.com gvt1.com prod.google.com pubads.g.doubleclick.net s0.2mdn.net static.doubleclick.net surveys.g.doubleclick.net youtube.com ytimg.com".split(" "),ye=["c.googlesyndication.com"];
function ze(a,b){b=void 0===b?window.location.protocol:b;var c=!1;Ae(a,ye)?c=!1:"https:"==b&&Ae(a,xe)&&(c=!0);if(c){b=new P(a);if("https"==b.h)return a;V(U.C(),"htp","1");Ld(b,"https");return b.toString()}return a}function Ae(a,b){return(new RegExp("^https?://([a-z0-9-]{1,63}\\.)*("+b.join("|").replace(/\./g,"\\.")+")(:[0-9]+)?([/?#]|$)","i")).test(a)};var Be=function(a){return(a=a.exec(E))?a[1]:""};(function(){if(Nb)return Be(/Firefox\/([0-9.]+)/);if(H||Ab||zb)return Ib;if(Rb)return ub()||F("iPad")||F("iPod")?Be(/CriOS\/([0-9.]+)/):Be(/Chrome\/([0-9.]+)/);if(Sb&&!(ub()||F("iPad")||F("iPod")))return Be(/Version\/([0-9.]+)/);if(Ob||Pb){var a=/Version\/(\S+).*Mobile\/(\S+)/.exec(E);if(a)return a[1]+"."+a[2]}else if(Qb)return(a=Be(/Android\s+([0-9.]+)/))?a:Be(/Version\/([0-9.]+)/);return""})();var Ce=function(){this.a=Ea()};Ce.prototype.reset=function(){this.a=Ea()};var De=function(a){var b=Ea();a=a.a+5E3-b;return 0<a?a:0};var Ee=function(a,b,c){this.id=a;this.g=b;this.a=c;this.ca=!1},Fe=function(){this.a=[]},Ge=function(){this.a=new Map;this.b=!1;this.h=new Fe;this.i=new Ee(0,0,!1);this.f=[this.h]},W=function(a){var b=He;if(b.b||b.a.has(a.id)||null==a.g&&null==a.control||0==a.ka)return b.i;var c=b.h;if(null!=a.control)for(var d=q(b.f),e=d.next();!e.done;e=d.next()){if(e=e.value,e.a.includes(a.control)){c=e;break}}else null!=a.G&&(c=a.G);d=0;null!=a.control?d=a.control.g:null!=a.g&&(d=a.g);a=new Ee(a.id,d,!!a.ra);c.a.push(a);
b.f.includes(c)||b.f.push(c);b.a.set(a.id,a);return a},Ie=function(){var a=He;return[].concat(ja(a.a.keys())).filter(function(b){b=this.a.get(b);return b.ca||b.a},a)};Ge.prototype.reset=function(){for(var a=q(this.a),b=a.next();!b.done;b=a.next())b=q(b.value),b.next(),b.next().value.ca=!1;this.b=!1};var He=new Ge;var Je=function(a){this.a=a};Je.prototype.b=function(a,b){a=q(this.a);for(var c=a.next();!c.done;c=a.next())if(c=b.get(c.value))c.ca=!0};var Ke=function(a,b){this.a=a;this.f=b};t(Ke,Je);Ke.prototype.b=function(a,b){Je.prototype.b.call(this,a,b);var c=[];a=[];for(var d=q(this.a),e=d.next();!e.done;e=d.next())e=e.value,b.get(e)?c.push(e):a.push(e);b=c.map(String).join(",")||"0";a=a.map(String).join(",")||"0";V(U.C(),"sei",b);V(U.C(),"nsei",a);V(U.C(),"bi",this.f)};var Le=function(){this.f=null;this.a="missing-id";this.b=!1},Ne=function(a){var b=null;try{b=document.getElementsByClassName("lima-exp-data")}catch(c){return Me("missing-element",a.a),null}if(1<b.length)return Me("multiple-elements",a.a),null;b=b[0];return b?b.innerHTML:(Me("missing-element",a.a),null)},Pe=function(){var a=Oe,b=Ne(a);if(null!==b)if(/^\s*$/.test(b)?0:/^[\],:{}\s\u2028\u2029]*$/.test(b.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,
"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))){var c=JSON.parse(b);b=c.experimentIds;c=c.binaryIdentifier;var d="string"===typeof c;d&&(a.a=c);"string"!==typeof b?Me("missing-flags",a.a):(d||Me("missing-binary-id",a.a),a.f=b)}else Me("invalid-json",a.a)};Le.prototype.reset=function(){this.f=null;this.a="missing-id"};var Qe=function(){Le.apply(this,arguments)};t(Qe,Le);var Me=function(a,b){var c=U.C();V(c,"eee",a);V(c,"bi",b)};wa(Qe);function Re(){return Se.split(",").map(function(a){return parseInt(a,10)}).filter(function(a){return!isNaN(a)})};var Te=new Fe;W({id:418572103,g:0});W({id:420706097,g:10});W({id:420706098,g:10});W({id:21061786,g:10});W({id:21061817,g:10});W({id:21061824,g:50});W({id:21061888,g:10});W({id:21061893,g:10});W({id:21062100,g:0});W({id:420706109,g:10});W({id:420706110,g:10});W({id:21062347,g:0});W({id:21063070,g:0});W({id:21063072,g:0});W({id:21063100,g:0});W({id:420706105,g:10});W({id:420706106,g:10});W({id:75259402,g:10});W({id:75259403,g:10});W({id:21064018,g:0});W({id:21064020,g:0});W({id:21064022,g:0});
W({id:21064024,g:0});W({id:21064075,g:0});W({id:21064201,g:50});var Ue=W({id:210640812,g:10});W({id:420706142,g:0});W({id:21064347,g:0});W({id:72811302,g:0});W({id:72811303,g:0});W({id:72811304,g:0});W({id:72811305,g:0});W({id:72811306,g:0});W({id:72811307,g:0});W({id:21064565,g:0});W({id:21064567,g:0});W({id:21064572,g:10});W({id:21064573,g:10});W({id:40819804,g:10});W({id:40819805,g:10});W({id:418572006,g:10});W({id:44711678,g:10});W({id:420706136,g:10});W({id:420706137,g:10});W({id:420706138,g:10});
W({id:420706139,g:10});W({id:420706140,g:10});W({id:420706141,g:10});W({id:21065285,g:1});W({id:21065286,g:1});W({id:21065287,g:10,ka:Nb});W({id:21065288,g:10,ka:Nb});W({id:72811314,g:0});W({id:44713399,g:10});W({id:44713400,g:10});W({id:44716336,g:10});W({id:44714510,g:0});W({id:44714743,g:0});W({id:44718225,g:0});W({id:44718226,g:0});W({id:42530094,g:50,G:Te});W({id:42530095,g:50,G:Te});W({id:42530173,g:10,G:Te});W({id:42530174,g:10,G:Te});W({id:668123728,g:10,G:Te});W({id:668123729,g:10,G:Te});
W({id:31061774,g:10});W({id:31061775,g:10});W({id:504733015,g:0});W({id:504733016,g:0});W({id:189176E3,g:50});W({id:189176001,g:50});W({id:40819802,g:10});W({id:40819803,g:10});W({id:44712632,g:10});W({id:44712633,g:10});W({id:44715336,g:10});W({id:44716179,g:10});W({id:44716180,g:10});W({id:44716182,g:0});W({id:42530380,g:0});W({id:44717156,g:10});W({id:44717924,g:10});W({id:44717925,g:10});W({id:44716185,g:0});W({id:44717873,g:50});W({id:44718840,g:10});W({id:44718841,g:10});
if("undefined"===typeof window.v8_flag_map){var Oe=Qe.C();Oe.b||(Pe(),Oe.b=!0);var Se=Oe.f,Ve;Oe.b||(Pe(),Oe.b=!0);Ve=Oe.a;if(null!=Se){var We=new Ke(Re(),Ve),Xe=He;Xe.b||(We.b(Xe.f,Xe.a),Xe.b=!0)}};var Ye=function(){if(!H)return!1;try{return new ActiveXObject("MSXML2.DOMDocument"),!0}catch(a){return!1}},Ze=H&&Ye();var X=function(a){I.call(this);this.h=a;this.b={}};Fa(X,I);var $e=[];X.prototype.H=function(a,b,c,d){Array.isArray(b)||(b&&($e[0]=b.toString()),b=$e);for(var e=0;e<b.length;e++){var f=od(a,b[e],c||this.handleEvent,d||!1,this.h||this);if(!f)break;this.b[f.key]=f}return this};var bf=function(a,b,c,d){af(a,b,c,d,void 0)},af=function(a,b,c,d,e,f){if(Array.isArray(c))for(var g=0;g<c.length;g++)af(a,b,c[g],d,e,f);else(b=nd(b,c,d||a.handleEvent,e,f||a.h||a))&&(a.b[b.key]=b)};
X.prototype.ja=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)this.ja(a,b[f],c,d,e);else c=c||this.handleEvent,d=y(d)?!!d.capture:!!d,e=e||this.h||this,c=pd(c),d=!!d,b=cd(a)?jd(a.b,String(b),c,d,e):a?(a=rd(a))?jd(a,b,c,d,e):null:null,b&&(wd(b),delete this.b[b.key])};var cf=function(a){Oa(a.b,function(b,c){this.b.hasOwnProperty(c)&&wd(b)},a);a.b={}};X.prototype.v=function(){X.V.v.call(this);cf(this)};
X.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var df=function(){};df.prototype.a=null;var ff=function(a){var b;(b=a.a)||(b={},ef(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var gf,hf=function(){};Fa(hf,df);var jf=function(a){return(a=ef(a))?new ActiveXObject(a):new XMLHttpRequest},ef=function(a){if(!a.b&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.b=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.b};gf=new hf;var Y=function(a){M.call(this);this.headers=new N;this.B=a||null;this.f=!1;this.w=this.a=null;this.J="";this.j=0;this.h=this.I=this.m=this.O=!1;this.u=0;this.s=null;this.X="";this.P=this.R=!1};Fa(Y,M);
var kf=/^https?$/i,lf=["POST","PUT"],mf=function(a,b){a.u=Math.max(0,b)},rf=function(a,b){if(a.a)throw Error("[goog.net.XhrIo] Object is active with another request="+a.J+"; newUri="+b);a.J=b;a.j=0;a.O=!1;a.f=!0;a.a=a.B?jf(a.B):jf(gf);a.w=a.B?ff(a.B):ff(gf);a.a.onreadystatechange=A(a.W,a);try{a.I=!0,a.a.open("GET",String(b),!0),a.I=!1}catch(e){nf(a);return}b=a.headers.clone();var c=Ja(b.L(),of),d=w.FormData&&!1;!(0<=Ga(lf,"GET"))||c||d||b.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
b.forEach(function(e,f){this.a.setRequestHeader(f,e)},a);a.X&&(a.a.responseType=a.X);"withCredentials"in a.a&&a.a.withCredentials!==a.R&&(a.a.withCredentials=a.R);try{pf(a),0<a.u&&(a.P=qf(a.a),a.P?(a.a.timeout=a.u,a.a.ontimeout=A(a.Y,a)):a.s=Hd(a.Y,a.u,a)),a.m=!0,a.a.send(""),a.m=!1}catch(e){nf(a)}},qf=function(a){return H&&Jb(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},of=function(a){return"content-type"==a.toLowerCase()};
Y.prototype.Y=function(){"undefined"!=typeof ra&&this.a&&(this.j=8,this.dispatchEvent("timeout"),this.abort(8))};var nf=function(a){a.f=!1;a.a&&(a.h=!0,a.a.abort(),a.h=!1);a.j=5;sf(a);tf(a)},sf=function(a){a.O||(a.O=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))};Y.prototype.abort=function(a){this.a&&this.f&&(this.f=!1,this.h=!0,this.a.abort(),this.h=!1,this.j=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),tf(this))};
Y.prototype.v=function(){this.a&&(this.f&&(this.f=!1,this.h=!0,this.a.abort(),this.h=!1),tf(this,!0));Y.V.v.call(this)};Y.prototype.W=function(){this.l||(this.I||this.m||this.h?uf(this):this.ea())};Y.prototype.ea=function(){uf(this)};
var uf=function(a){if(a.f&&"undefined"!=typeof ra&&(!a.w[1]||4!=vf(a)||2!=wf(a)))if(a.m&&4==vf(a))Hd(a.W,0,a);else if(a.dispatchEvent("readystatechange"),4==vf(a)){a.f=!1;try{var b=wf(a);a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=String(a.J).match(fc)[1]||null;if(!f&&w.self&&w.self.location){var g=w.self.location.protocol;f=g.substr(0,g.length-1)}e=!kf.test(f?f.toLowerCase():"")}d=e}d?(a.dispatchEvent("complete"),
a.dispatchEvent("success")):(a.j=6,sf(a))}finally{tf(a)}}},tf=function(a,b){if(a.a){pf(a);var c=a.a,d=a.w[0]?va:null;a.a=null;a.w=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},pf=function(a){a.a&&a.P&&(a.a.ontimeout=null);a.s&&(w.clearTimeout(a.s),a.s=null)},vf=function(a){return a.a?a.a.readyState:0},wf=function(a){try{return 2<vf(a)?a.a.status:-1}catch(b){return-1}},xf=function(a){try{return a.a?a.a.responseText:""}catch(b){return""}},yf=function(a,b){if(a.a&&4==vf(a))return a=
a.a.getResponseHeader(b),null===a?void 0:a};var zf=function(){};zf.prototype.get=function(a,b){return Af(a,b)};
var Af=function(a,b){return Bf(a,!0,b).then(function(c){return Promise.resolve(c)},function(c){return c instanceof Error&&6==c.message?Bf(a,!1,b):Promise.reject(c)})},Bf=function(a,b,c){var d=new Y;d.R=b;mf(d,De(c));var e=new X;return new Promise(function(f,g){bf(e,d,"success",function(){try{var h=d.a?d.a.responseXML:null}catch(u){h=null}if(null==h)if(h=xf(d),"undefined"!=typeof DOMParser){var k=new DOMParser;h=rb(h,null);h=k.parseFromString(qb(h),"application/xml")}else if(Ze){k=new ActiveXObject("MSXML2.DOMDocument");
k.resolveExternals=!1;k.validateOnParse=!1;try{k.setProperty("ProhibitDTD",!0),k.setProperty("MaxXMLSize",2048),k.setProperty("MaxElementDepth",256)}catch(u){}k.loadXML(h);h=k}else throw Error("Your browser does not support loading xml documents");k=Ue.ca||Ue.a;var l;if(l=h&&h.documentElement)(l=h.documentElement)&&"VAST"!=!l.nodeName?(l=l.getAttribute("version"))?(l=parseInt(l,10),l=null==l||isNaN(l)?null:l):l=null:l=null,l=null==l||2>l||4<l?!1:!0;if(!l&&k){k={vastUrl:a.substring(0,200),responseText:xf(d).substring(0,
200),status:wf(d),contentType:yf(d,"Content-Type"),acao:yf(d,"Access-Control-Allow-Origin"),acac:yf(d,"Access-Control-Allow-Credentials"),origin:window.location.origin};l=U.C();for(var n=q(Object.keys(k)),r=n.next();!r.done;r=n.next())r=r.value,V(l,r,k[r])}f(h);e.F();d.F()});bf(e,d,["error","timeout"],function(){g(Error(d.j));e.F();d.F()});rf(d,ze(a))})};/*

Math.uuid.js (v1.4)
http://www.broofa.com
mailto:robert@broofa.com
Copyright (c) 2010 Robert Kieffer
Dual licensed under the MIT and GPL licenses.
*/
var Cf=function(a){this.a=a};var Df=function(){this.b=new N;this.a=null},Ef=function(a){var b=Math.random(),c=0,d=a.b.D();d.forEach(function(){c+=0});var e=1<c?c:1;a.a=null;for(var f=0,g=0;g<d.length;++g)if(f+=0,f/e>=b){a.a=d[g];break}};var Ff=function(a){this.a=a},Hf=function(){var a=Gf();a:{if(Pa(a.a,"disableExperiments")&&(a=a.a.disableExperiments,"boolean"===typeof a))break a;a=!1}return a},If=function(a){if(Pa(a.a,"forceExperimentIds")){a=a.a.forceExperimentIds;var b=[],c=0;"array"==x(a)&&a.forEach(function(d){"number"===typeof d&&(b[c++]=d)});return b}return null};var Jf=function(a,b){this.a=a;this.depth=b},Lf=function(){var a=tc(),b=Math.max(a.length-1,0),c=wc(a);a=c.a;var d=c.b,e=c.f,f=[];c=function(h,k){return null==h?k:h};e&&f.push(new Jf([e.url,e.ia?2:0],c(e.depth,1)));d&&d!=e&&f.push(new Jf([d.url,2],0));a.url&&a!=e&&f.push(new Jf([a.url,0],c(a.depth,b)));var g=Ha(f,function(h,k){return f.slice(0,f.length-k)});!a.url||(e||d)&&a!=e||(d=kc(a.url))&&g.push([new Jf([d,1],c(a.depth,b))]);g.push([]);Ha(g,function(h){return Kf(b,h)})};
function Kf(a,b){var c=Ia(b,function(e,f){return Math.max(e,f.depth)},-1),d=Ma(c+2);d[0]=a;B(b,function(e){return d[e.depth+1]=e.a});return d};var Gf=function(){var a=Mf;if(null==a.a){var b={};var c=(new P(window.location.href)).a;if(Zd(c,"tcnfp"))try{b=JSON.parse(c.get("tcnfp"))}catch(d){}a.a=new Ff(b)}return a.a},Mf=new function(){this.a=null;try{Lf()}catch(a){}};var Pf=function(){this.b=!1;this.a=new N;Nf(this);var a=Gf();a=If(a);null!=a&&(this.b=!0,Of(this,a.map(String)))},Qf=null,Nf=function(a){Hf()||a.a.D().forEach(function(b){Ef(b)})},Of=function(a,b){b.forEach(function(c){var d=Number(c);c="FORCED_PUB_EXP_LAYER_"+c;if(!(isNaN(d)||0>=d||Va(null==c?"":String(c)))){a.b=!0;var e=a.a.get(c);null==e&&(e=new Df,a.a.set(c,e));e.a=new Cf(d)}})},Rf=function(){Qf||(Qf=new Pf);var a=Qf;if(!a.b&&(Hf()||null!=w.G_testRunner))return"";var b=[];a.a.D().forEach(function(c){(c=
c.a)&&b.push(c.a)});a=Ie();return b.concat(a).sort().join(",")};var Sf=!1,Tf=function(a){if(a=a.match(/[\d]+/g))a.length=3};
(function(){if(navigator.plugins&&navigator.plugins.length){var a=navigator.plugins["Shockwave Flash"];if(a&&(Sf=!0,a.description)){Tf(a.description);return}if(navigator.plugins["Shockwave Flash 2.0"]){Sf=!0;return}}if(navigator.mimeTypes&&navigator.mimeTypes.length&&(a=navigator.mimeTypes["application/x-shockwave-flash"],Sf=!(!a||!a.enabledPlugin))){Tf(a.enabledPlugin.description);return}if("undefined"!=typeof ActiveXObject){try{var b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7");Sf=!0;Tf(b.GetVariable("$version"));
return}catch(c){}try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");Sf=!0;return}catch(c){}try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),Sf=!0,Tf(b.GetVariable("$version"))}catch(c){}}})();var Wf=function(){var a="h.3.383.0";null!=Uf&&(a+="/n."+Uf,null!=Vf&&(a+="/"+Vf));return a},Vf=null,Uf=null;var Xf=function(){var a=window,b=document;return new P(a.parent==a?a.location.href:b.referrer)},Yf=function(a,b){a.a.set("url","");try{var c=2083-a.toString().length-1;if(0>=c)return a.toString();for(var d=b.slice(0,c),e=encodeURIComponent(d),f=c;0<f&&e.length>c;)d=b.slice(0,f--),e=encodeURIComponent(d);a.a.set("url",d)}catch(g){}return a.toString()};var Zf=function(a){M.call(this);this.j=a||"goog_"+tb++;this.h=[];this.f=!1};t(Zf,M);Zf.prototype.connect=function(){for(this.f=!0;0!=this.h.length;){var a=this.h.shift();this.sendMessage(a.name,a.type,a.data)}};Zf.prototype.sendMessage=function(){};function $f(a){a=ze(a,le()?"https":window.location.protocol);if(le())ag(a);else try{a&&(ce(a)?ge(a):ke(a))}catch(b){}}function ag(a){(new zf).get(a,new Ce).then(function(){},function(){})};var bg=function(){this.b=.01>Math.random();this.a=Math.floor(4503599627370496*Math.random())},dg=function(){var a=bg.C();var b=void 0===b?{}:b;if(null==w.G_testRunner&&a.b){b.lid=11;b.sdkv=Wf();var c=Rf();Va(null==c?"":String(c))||(b.e=c);b=cg(a,b);var d=new P("http://pagead2.googlesyndication.com/pagead/gen_204");Oa(b,function(e,f){d.a.set(f,null==e?"":"boolean"==typeof e?e?"t":"f":""+e)},a);a=Xf();Ld(d,a.h);a=d.toString();b=d.a.get("url");null!=b&&(F("Trident")||F("MSIE"))&&2083<a.length&&(a=Yf(d,
b));$f(a)}},cg=function(a,b){b.id="ima_html5";var c=Xf();b.c=a.a;b.domain=c.b;return b};wa(bg);var eg=function(a,b,c,d,e){e=void 0===e?"":e;L.call(this,a);this.M=b;this.ba=c;this.ma=d;this.la=e};t(eg,L);eg.prototype.toString=function(){return""};var fg=function(a,b){Zf.call(this,b);this.m=a;this.a=null;this.s=new X(this);this.s.H(window,"message",this.u)};t(fg,Zf);var gg=function(a){if(null==a||"string"!==typeof a||0!=a.lastIndexOf("ima://",0))return null;a=a.substr(6);try{return JSON.parse(a)}catch(b){return null}};fg.prototype.sendMessage=function(a,b,c){null!=this.a&&null!=this.a.postMessage&&this.a.postMessage(hg(this,a,b,c),"*");null!=this.a&&null==this.a.postMessage&&dg()};fg.prototype.v=function(){mc(this.s);this.a=null;Zf.prototype.v.call(this)};
fg.prototype.u=function(a){a=a.b;var b=gg(a.data);if(ig(this,b)){if(null==this.a)this.a=a.source,this.f||this.connect();else if(this.a!=a.source)return;ig(this,b)&&this.dispatchEvent(new eg(b.name,b.type,b.data||{},b.sid,a.origin))}};var hg=function(a,b,c,d){var e={};e.name=b;e.type=c;null!=d&&(e.data=d);e.sid=a.j;e.channel=a.m;return"ima://"+Cd(e)},ig=function(a,b){if(null==b)return!1;var c=b.channel;if(null==c||c!=a.m)return!1;b=b.sid;return null==b||"*"!=a.j&&b!=a.j?!1:!0};var jg=function(a,b,c,d,e,f){eg.call(this,a,b,c,d,e);this.b=f};t(jg,eg);var kg=function(a,b){M.call(this);this.j=a;this.h=b;this.a={};this.f=new X(this);this.f.H(window,"message",this.m)};t(kg,M);var lg=function(a,b){var c=b.b;if(a.a.hasOwnProperty(c)){a=a.a[c];c=b.type;var d=b.M;b=b.ba;a.f?a.sendMessage(c,d,b):a.h.push({name:c,type:d,data:b})}},mg=function(a,b,c,d){a.a.hasOwnProperty(b)||(c=new fg(b,c),a.f.H(c,a.j,function(e){this.dispatchEvent(new jg(e.type,e.M,e.ba,e.ma,e.la,b))}),c.a=d,c.connect(),a.a[b]=c)};
kg.prototype.v=function(){this.f.F();for(var a in this.a)mc(this.a[a]);M.prototype.v.call(this)};kg.prototype.m=function(a){a=a.b;var b=gg(a.data);if(null!=b){var c=b.channel;if(this.h&&!this.a.hasOwnProperty(c)){var d=b.sid;mg(this,c,d,a.source);this.dispatchEvent(new jg(b.name,b.type,b.data||{},d,a.origin,c))}}};function ng(){return!!ua("googletag.cmd",window)}function og(){var a=ua("googletag.console",window);return null!=a?a:null}var pg=function(){X.call(this);this.f=new kg("gpt",!0);lc(this,Da(mc,this.f));this.H(this.f,"gpt",this.m);this.a=null;ng()||window.top===window||(this.a=new kg("gpt",!1),lc(this,Da(mc,this.a)),this.H(this.a,"gpt",this.j))};t(pg,X);
pg.prototype.m=function(a){var b=a.la,c="//imasdk.googleapis.com".match(fc);b=b.match(fc);if(c[3]==b[3]&&c[4]==b[4])if(null!=this.a)mg(this.a,a.b,a.ma,window.parent),null!=this.a&&lg(this.a,a);else if(c=a.ba,null!=c&&void 0!==c.scope){b=c.scope;c=c.args;var d;if("proxy"==b)c=a.M,"isGptPresent"==c?d=ng():"isConsolePresent"==c&&(d=null!=og());else if(ng())if("pubads"==b||"companionAds"==b){d=a.M;var e=window.googletag;if(null!=e&&null!=e[b]&&(e=e[b](),null!=e&&(d=e[d],null!=d)))try{var f=d.apply(e,
c)}catch(g){}d=f}else if("console"==b){if(f=og(),null!=f&&(e=f[a.M],null!=e))try{e.apply(f,c)}catch(g){}}else if(null===b){d=a.M;f=window;if(["googleGetCompanionAdSlots","googleSetCompanionAdContents"].includes(d)&&(d=f[d],null!=d))try{e=d.apply(f,c)}catch(g){}d=e}void 0!==d&&(a.ba.returnValue=d,lg(this.f,a))}};pg.prototype.j=function(a){lg(this.f,a)};var qg=window,rg=ua("google.ima.gptProxyInstance",qg);if(null==rg){var sg=rg=new pg,tg=["google","ima","gptProxyInstance"],Z=qg||w;tg[0]in Z||"undefined"==typeof Z.execScript||Z.execScript("var "+tg[0]);for(var ug;tg.length&&(ug=tg.shift());)tg.length||void 0===sg?Z[ug]&&Z[ug]!==Object.prototype[ug]?Z=Z[ug]:Z=Z[ug]={}:Z[ug]=sg};})();
